spring:
  application:
    name: radiozerver
    jmx:
      enabled: false
    datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:mem:bootexample;MODE=MySQL

  resources:
    cache-period: 3600
server:
  port: 9000
  compression:
    enabled: true

spring:
  profiles: test
  h2:
    console:
      enabled: true

    spring.jpa:
        hibernate.ddl-auto: create-drop

logging:
  file: bootcrud.log
  level:
    org.springframework: debug

banner:
  image:
    location: = banner.jpg
